# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Automatic Changelog Generator
      uses: CharMixer/auto-changelog-action@v1.1
      with:
        # Username of the owner of target GitHub repo (default: extracted from $GITHUB_REPOSITORY)
        user: ForyxCraft
        # Name of project on GitHub (default: extracted from $GITHUB_REPOSITORY)
        project: ForyxLIB
        # Limit pull requests to the release branch, such as master or release (required, default: master)
        release_branch: master
        # Output file. To print to STDOUT instead, use blank as path. (required, default: CHANGELOG.md)
        output: CHANGELOG.md
        # Optional base file to append generated changes to (default: HISTORY.md)
        base: HISTORY.md
        # To make more than 50 requests per hour your GitHub token is required. You can generate it at: https://github.com/settings/tokens/new<Paste>
        token: 3d44750bb50d9dd7b3a176b8df503acacc89f5eb
        # Put the unreleased changes in the specified release number.
        future_release: Unreleased
