# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run setup
      - run: npm run build --if-present
      - name: Automatic Changelog Generator
        uses: CharMixer/auto-changelog-action@v1.1
        with:
          # Username of the owner of target GitHub repo (default: extracted from $GITHUB_REPOSITORY)
          user: FlawCra
          # Name of project on GitHub (default: extracted from $GITHUB_REPOSITORY)
          project: FlawCraLIB
          # Limit pull requests to the release branch, such as master or release (required, default: master)
          release_branch: master
          # Output file. To print to STDOUT instead, use blank as path. (required, default: CHANGELOG.md)
          output: CHANGELOG.md
          # Optional base file to append generated changes to (default: HISTORY.md)
          base: HISTORY.md
          # Put the unreleased changes in the specified release number.
          future_release: Unreleased
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
